emote-provider:
  # what emote provider to use: 'local' or 'http'
  # emote provider is responsible for emote management and resource pack generation
  use: local

  # settings for local emote provider
  local:
    # resource pack generator
    pack:
      prompt: Chat emotes!
      height: 10
      ascent: 8
    # minecraft server hostname override (set to disable auto detection)
    hostname-override: null
    # resource pack server
    http.port: 25765

  # settings for http emote provider
  http:
    headers:
      user-agent: chatemotes/1.0
      # authorization: token
    urls:
      emotes:
        # HTTP GET <- [{ "name": "Kappa", "char": "ยง" }]
        list: http://localhost:8080/emotes

        # HTTP PUT -> { "name": "Kappa", "url": "https://..." }
        add: http://localhost:8080/emote

        # HTTP DELETE
        delete: http://localhost:8080/emote/{name}
      pack:
        download: http://localhost:8080/resource_pack.zip
        # HTTP GET <- { "hash": "..." }
        hash: http://localhost:8080/hash
