emote-provider:
  # local | http
  use: local
  local:
    # Resource pack generator
    pack:
      prompt: Chat emotes!
      height: 10
      ascent: 7
    # Minecraft server hostname override (set to disable auto detection)
    hostname-override: null
    # Resource pack server
    http.port: 25765
  http:
    headers:
      user-agent: chatemotes/1.0
    urls:
      emotes:
        # HTTP GET
        # return [{ "name": "Kappa", "char": "ยง" }]
        list: http://localhost:8080/emotes

        # HTTP PUT -> { "name": "Kappa", "url": "https://..." }
        add: http://localhost:8080/emote

        # HTTP DELETE
        delete: http://localhost:8080/emote/{name}
      pack:
        download: http://localhost:8080/chat_emotes.zip?h={hash}
        # HTTP GET
        # return { "hash": "..." }
        hash: http://localhost:8080/resource-pack-hash
