name: ChatEmotes
version: ${pluginVersion}
api-version: 1.19
main: me.apyr.chatemotes.ChatEmotes
softdepend: [kotlin-stdlib]
description: Use custom png-emotes in chat. Based on server resource pack.
authors: [apyrr, crashmax-dev]
website: https://github.com/apyrr/spigot-chatemotes
commands:
  emote:
    description: List and manage chat emotes
    aliases: [e, em]
    usage: /<command>
permissions:
  chatemotes.manage:
    description: Allows refreshing resource pack, adding & deleting emotes
    default: op
