name: Build ChatEmotes

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Create release
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');

            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              draft: false,
              generate_release_notes: true,
              prerelease: true,
              tag_name: '1.' + process.env.GITHUB_RUN_NUMBER,
            });

            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              origin: release.data.upload_url,
              release_id: release.data.id,
              name: 'ChatEmotes.jar',
              data: fs.readFileSync('build/libs/ChatEmotes.jar')
            });
