name: Build ChatEmotes

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload jars to GitHub
        uses: actions/upload-artifact@master
        with:
          name: ChatEmotes plugin jars
          path: build/libs/*.jar
