name: Build ChatEmotes

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Save plugin version
        run: echo "PLUGIN_VERSION=$(./gradlew -q printPluginVersion)" >> $GITHUB_OUTPUT
        id: plugin-version

      - name: Create release
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');

            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              draft: false,
              prerelease: true,
              tag_name: 'v${{ steps.plugin-version.outputs.PLUGIN_VERSION }}'
            });

            const uploadAsset = (name, path) => github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              origin: release.data.upload_url,
              release_id: release.data.id,
              name: name,
              data: fs.readFileSync(path)
            });

            await uploadAsset('ChatEmotes.jar', 'build/libs/ChatEmotes.jar');
            await uploadAsset('ChatEmotes-nostdlib.jar', 'build/libs/ChatEmotes-nostdlib.jar');
